# Generated by Django 5.1.2 on 2025-03-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrispine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('celular', models.CharField(max_length=14)),
                ('especialidade', models.CharField(max_length=100)),
                ('registro', models.CharField(max_length=100)),
            ],
        ),
    ]
