# Generated by Django 5.1.2 on 2025-03-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrispine', '0003_consulta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='celular',
            new_name='telefone',
        ),
        migrations.RenameField(
            model_name='profissional',
            old_name='celular',
            new_name='telefone',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
