# Generated by Django 5.1.2 on 2025-03-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrispine', '0004_rename_celular_paciente_telefone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('numero_cartao', models.CharField(max_length=100)),
                ('data_validade', models.DateField()),
                ('cvv', models.IntegerField()),
                ('valor', models.FloatField()),
            ],
        ),
    ]
